version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-web
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - portfolio-network

  # Optional: Add a reverse proxy for SSL/domain management
  # nginx-proxy:
  #   image: nginx:alpine
  #   container_name: nginx-proxy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./proxy.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - portfolio
  #   networks:
  #     - portfolio-network

networks:
  portfolio-network:
    driver: bridge
